### ISSUE TITLE
Need to manage missing orbit for other spacecraftActors

### ISSUE THREAD

**Issue by GabrieleMeoni** [aidotse/PASEOS#77]
# Issue
## Problem Description
At the moment, if you try to add another spacecraftActor mssing of the orbit to PASEOS, a not clear error is raised.
## Expected Behavior
An appropriate error shall be raised suggesting to add  "ActorBuilder.set_orbit(...)" if the actor is a spacecraft actor, when adding another actor.
## What Needs to be Done
If the other actor is a SpacecraftActor, it is necessary to check if an orbit is assigned upon a request to be added to PASEOS and, otherwise, raise an appropriate error.
## How Can It Be Tested or Reproduced
Try the following code:

```py

import pykep as pk
import paseos
from paseos import ActorBuilder, SpacecraftActor


# Define an actor of type SpacecraftActor of name mySat (that will be the local actor)
local_actor = ActorBuilder.get_actor_scaffold(name="mySat", 
                                       actor_type=SpacecraftActor, 
                                       epoch=pk.epoch(0))

other_actor = ActorBuilder.get_actor_scaffold(name="other", 
                                       actor_type=SpacecraftActor, 
                                       epoch=pk.epoch(0))
# Define the central body as Earth by using pykep APIs.
earth = pk.planet.jpl_lp("earth")

# Let's set the orbit of sat_actor.
ActorBuilder.set_orbit(actor=local_actor, 
                       position=[10000000, 0, 0], 
                       velocity=[0, 8000.0, 0], 
                       epoch=pk.epoch(0), central_body=earth)


# Add a power device                                     
ActorBuilder.set_power_devices(actor=local_actor, 
                               battery_level_in_Ws=100, # Battery level at the start of the simulation in Ws
                               max_battery_level_in_Ws=2000, # Max battery level in Ws
                               charging_rate_in_W=10) # Charging rate in W


# initialize PASEOS simulation
sim = paseos.init_sim(local_actor) 
sim.add_known_actor(other_actor)
```

**Comment by Kd-Here** [comment]
Hey @GabrieleMeoni can I try it.
I know I am to beginner for advance project but love ML lib .

**Comment by GabrieleMeoni** [comment]
Hey @Kd-Here,

sure, give it a try! Please, refer to our guidelines for contribution to know how to proceed: https://github.com/aidotse/PASEOS#contributing.

Looking forward to your pull-request!

**Comment by gomezzz** [comment]
@GabrieleMeoni I think this was already fixed at some point. Your example runs without error. And if I, e.g., try to do 

`print(local_actor.is_in_line_of_sight(other_actor, epoch=local_actor.local_time))`

I get

```
Traceback (most recent call last):
  File ".../77_issue.py", line 44, in <module>
    print(local_actor.is_in_line_of_sight(other_actor, epoch=local_actor.local_time))
  File ".../../paseos/actors/base_actor.py", line 277, in is_in_line_of_sight
    return is_in_line_of_sight(
  File ".../../paseos/communication/is_in_line_of_sight.py", line 204, in is_in_line_of_sight
    return _is_in_line_of_sight_spacecraft_to_spacecraft(
  File ".../../paseos/communication/is_in_line_of_sight.py", line 58, in _is_in_line_of_sight_spacecraft_to_spacecraft
    other_actor_pos, _ = other_actor.get_position_velocity(epoch)
  File ".../../paseos/actors/base_actor.py", line 240, in get_position_velocity
    raise NotImplementedError(
NotImplementedError: No suitable way added to determine actor velocity. Set an orbit with ActorBuilder.
```

Which is exactly what you asked for, I think.

Please re-open if not.
